derlebaglacalistir: derle bagla calistir

derle:
	g++ -c -I "./include" ./src/Dugum.cpp -o ./lib/Dugum.o
	g++ -c -I "./include" ./src/Kuyruk.cpp -o ./lib/Kuyruk.o
	g++ -c -I "./include" ./src/main.cpp -o ./lib/main.o

bagla:
	g++  ./lib/Dugum.o ./lib/Kuyruk.o ./lib/main.o -o ./bin/program.exe
calistir:
	./bin/program.exe